[theme]
background = "#000000"
primary = "#8EC07C"
secondary = "#458588"
title = "#458588"
playing = "#458588"
playing_selected = "#73C390"
playing_bg = "#070707"
highlight = "#d65d03"
highlight_bg = "#000000"
error = "#282828"
error_bg = "#FB4934"
statusbar = "#000000"
statusbar_progress = "#458588"
statusbar_bg = "#458588"
cmdline = "#000000"
cmdline_bg = "#458588"
