#! /bin/sh
sxhkd &
compton --config /home/tux/.config/compton/compton.conf &
wmname LG3D &
feh --bg-fill /home/tux/.config/bspwm/fondos/35.png &
$HOME/.config/polybar/launch.sh &
bspc config pointer_modifier mod1
pgrep -x sxhkd > /dev/null || sxhkd &


#======================= my monitors
#bspc monitor -d Ӎᴜs Ƒἶʅ ἶოց Ƒαх Ƭuχ Є†c ἶო Ɲ℮ʈ ł¢ X
#laptop
bspc monitor DP-1  -d Ɲ℮ʈ ł¢ Ƒἶʅ
#LG
bspc monitor eDP-1 -d Ƒαх Ӎᴜs ἶოց pdf
#samsung
bspc monitor HDMI-1 -d Ƭuχ Є†c ἶო
#=====================================
bspc config border_width         3
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#=========================== config focus
bspc config focus_follows_pointer true
bspc config focused_border_color '#83a598'
#pointer_follows_monitor true
#bspc config focus_follows_pointer false

#========================== Desktop 1
bspc rule -a firefox desktop='^1'
bspc rule -a Google-chrome desktop='^1' state=floating follow=on

#========================== Desktop 2
bspc rule -a vlc desktop='^2'
bspc rule -a mpv desktop='^2'

#========================== Desktop 3
bspc rule -a Org.gnome.Nautilus desktop='^3'

#========================== Desktop 4
bspc rule -a zoom desktop='^4'
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a whatsapp-nativefier-d40211 desktop='^4'

#========================== Desktop 5
bspc rule -a Gnome-terminal desktop='^5'

#========================== Desktop 6
bspc rule -a feh desktop='^6'

#========================== Desktop 7
bspc rule -a libreoffice-startcenter desktop='^7'
bspc rule -a Evince desktop='^7'


#========================== Desktop 8
bspc rule -a Terminator desktop='^8'

#========================== Desktop 9
bspc rule -a Filezilla desktop='^9'

#========================== Desktop 0
bspc rule -a Tilix desktop='^0'
bspc rule -a Subl desktop='^0'
bspc rule -a Eclipse desktop='^0'
bspc rule -a pycharm desktop='^0'
bspc rule -a Code desktop='^0'

